### PR TITLE
Support FluidX labSampleId change to a string

### PR DESCRIPTION
**Pull request by gerlv**
## Overview

GelReportModels changed labSampleId from an integer to a string, but 100k still uses an integer.

## Changes

- Change older models so they use type `any`, and build 7.7 will use `string`
- Found 2 issues with the previous models - in one place a field wasn't marked as optional, and in InterpretationRequest bigWigs were referring to a wrong JSON field
- Updated dependencies - removed doc generation as we don't use it, upgraded jest, typescript - tests run faster now, and run `npm audit fix`
- Increased version

Closes: INTPORTAL-715

### CODE REVIEW

**Comment by gerlv** [comment]
@punalsc could you point dependency in cva-frontend to this branch and check if it works as expected? I'll do the same for portal

**Comment by gerlv** [comment]
@polyccon @punalsc do you have any comments for this review?

**Comment by polyccon** [comment]
That's a lot of files to review, my only comment would be to just ensure that all the changes between the previous build are included in the new one 7.7 or at least the ones we think might be needed - could you perhaps list them in the description?

**Comment by punalsc** [comment]
> @punalsc could you point dependency in cva-frontend to this branch and check if it works as expected? I'll do the same for portal

Sorry, just got this notification.
When you say this branch, should'nt it be the `master` branch?

**Comment by gerlv** [comment]
> That's a lot of files to review, my only comment would be to just ensure that all the changes between the previous build are included in the new one 7.7 or at least the ones we think might be needed - could you perhaps list them in the description?

yep, it's there - switch from int to string

**Comment by punalsc** [comment]
> > > @punalsc could you point dependency in cva-frontend to this branch and check if it works as expected? I'll do the same for portal
> > 
> > 
> > Sorry, just got this notification.
> > When you say this branch, should'nt it be the `master` branch?
> 
> Not yet, this hasn't been merged yet

Ok, i will check if it's working first, from this branch.

**Review by polyccon — APPROVED** [review]

**Comment by punalsc** [comment]
I dont have any further comments.

**Comment by punalsc** [comment]
> @punalsc could you point dependency in cva-frontend to this branch and check if it works as expected? I'll do the same for portal

I have updated the dependancy to CVA, and it's working fine.

**Pull request merged**
